// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package hello

// Injectors from wire.go:

func InitializeSayer(tt TransformType) *ExactSayer {
	transformer := NewTransform(tt)
	exactSayer := NewSayer(transformer)
	return exactSayer
}
