// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/hello"
	"example/valet"
)

// Injectors from wire.go:

func InitializeValetParker(message string) valet.ValetPark {
	transformer := hello.NewDefaultTransformer()
	sayer := hello.NewSayer(transformer)
	valetPark := valet.NewValetParker(sayer)
	return valetPark
}
