// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

// Injectors from wire.go:

func InitializeTransformHandler() *TransformHandler {
	transformHandler := NewTransformHandler()
	return transformHandler
}
