// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"example/config"
	"example/handlers"
)

// Injectors from wire.go:

func InitializeServer() (*Server, error) {
	configuration, err := config.GetCfg()
	if err != nil {
		return nil, err
	}
	transformHandler := handlers.NewTransformHandler(configuration)
	server := NewServer(configuration, transformHandler)
	return server, nil
}
